spring:

  redis:
    host: ${REDIS_NET:127.0.0.1}
    password: 123456
    port: 6379
    database: 0


  datasource:
    url: jdbc:mysql://${MYSQL_NET:localhost}:3306/election?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



